// data.js — GTM Ontology dummy data for Salesforce.com (sample customer)
// Exposed as window.GTM_DATA
(function () {
  // ── Source evidence helper ────────────────────────────────────────────
  // type: 'Website' | 'Call recording' | 'Email' | 'CRM note'
  function S(type, label, snippet, when, ref) {
    return { type, label, snippet, when, ref };
  }

  // ── Row helper — fills sensible defaults ──────────────────────────────
  function R(o) {
    return Object.assign(
      {
        ttlDays: null, priority: 'Medium', claimType: 'Inferred',
        confidence: 'Medium', status: 'Suggested', safeForOutreach: null,
        sources: [],
      },
      o
    );
  }

  const motions = [
    { id: 'data_360_ai_readiness', name: 'Data 360 — AI Readiness', short: 'AI Readiness',
      products: ['Data 360', 'Agentforce'], status: 'Needs Review', progress: 71 },
    { id: 'sales_cloud_rep_productivity', name: 'Sales Cloud — Rep Productivity', short: 'Rep Productivity',
      products: ['Sales Cloud', 'Agentforce Sales'], status: 'Needs Review', progress: 62 },
    { id: 'agentforce_sales_automation', name: 'Agentforce — Sales Agent Automation', short: 'Sales Agent Automation',
      products: ['Agentforce', 'Sales Cloud'], status: 'Suggested', progress: 49 },
    { id: 'service_cloud_contact_center', name: 'Service Cloud — Contact Center Modernization', short: 'Contact Center Modernization',
      products: ['Service Cloud', 'Agentforce Service'], status: 'Suggested', progress: 54 },
    { id: 'mulesoft_integration_modernization', name: 'MuleSoft — Integration Modernization', short: 'Integration Modernization',
      products: ['MuleSoft', 'Data 360'], status: 'Needs Review', progress: 58 },
  ];

  const rows = [
    // ═══════════════ DATA 360 — AI READINESS ═══════════════
    R({ id: 'p_data_leader', category: 'Buyer Persona', value: 'Data Leader',
      description: 'Owns data platforms, governance, customer profiles, and AI readiness across the enterprise.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'CDO · VP Data · Head of Data Platform',
      confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      titles: 'Chief Data Officer · VP Data · Head of Data Platform · Director, Data Engineering',
      responsibilities: 'Data architecture, governance, customer 360 strategy, AI/ML enablement, data quality.',
      fit: 'Enterprise (5k+ employees), multiple data silos, active AI or personalization initiative.',
      disqualifiers: 'Single-system shops, no analytics function, sub-200 employees.',
      relatedPersona: 'CIO / IT Executive · AI Transformation Leader',
      recommendedAgentUse: 'Target data and IT leaders at enterprise accounts showing AI readiness or customer-data modernization signals.',
      sources: [
        S('Website', 'Data 360 product page', 'Unify customer data and activate trusted profiles across every interaction.', 'Mar 12, 2026', 'salesforce.example/products/data-360'),
        S('Call recording', 'Discovery — Northern Trail (CDO)', '"My mandate this year is getting our data AI-ready — right now it\u2019s scattered across nine systems."', 'Feb 28, 2026', 'Gong · 42 min'),
        S('CRM note', 'Acct: Cloud Kicks — exec briefing', 'New CDO prioritizing a single source of truth for customer data ahead of GenAI rollout.', 'Mar 04, 2026', 'Account activity'),
      ] }),
    R({ id: 'p_cio', category: 'Buyer Persona', value: 'CIO / IT Executive',
      description: 'Accountable for platform consolidation, security, and the technology roadmap that enables AI.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'CIO · CTO · VP IT',
      confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      titles: 'CIO · CTO · SVP Technology · VP Enterprise Architecture',
      responsibilities: 'Platform strategy, vendor consolidation, security & compliance, cost governance.',
      fit: 'Sprawling app portfolio, board-level AI pressure, active consolidation program.',
      disqualifiers: 'No central IT, fully outsourced technology.',
      recommendedAgentUse: 'Engage on consolidation ROI and trusted-AI foundations; pair with Data Leader persona.',
      sources: [
        S('Website', 'AI readiness solution page', 'Ground AI in trusted, governed enterprise data.', 'Mar 12, 2026', 'salesforce.example/solutions/ai-readiness'),
        S('Email', 'Inbound — Acme CIO', '"We need to rationalize the stack before we scale AI. Who owns the data layer story?"', 'Mar 06, 2026', 'inbound@'),
      ] }),
    R({ id: 'p_marketing_ops', category: 'Buyer Persona', value: 'Marketing Operations Leader',
      description: 'Activates unified customer profiles for segmentation, personalization, and journeys.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'VP Marketing Ops · Head of CRM · Lifecycle Lead',
      confidence: 'Medium', claimType: 'Inferred', status: 'Needs Admin Review', priority: 'Medium',
      titles: 'VP Marketing Operations · Director Lifecycle · Head of Martech',
      responsibilities: 'Audience activation, journey orchestration, martech stack, attribution.',
      fit: 'B2C / B2B2C, large addressable base, personalization mandate.',
      disqualifiers: 'No marketing automation, low data volume.',
      recommendedAgentUse: 'Use when personalization or audience-activation signals appear; secondary to Data Leader.',
      sources: [
        S('Website', 'Marketing personalization page', 'Activate trusted profiles for real-time personalization.', 'Mar 12, 2026', 'salesforce.example/solutions/personalization'),
      ] }),
    R({ id: 'p_ai_transformation', category: 'Buyer Persona', value: 'AI Transformation Leader',
      description: 'Drives enterprise AI strategy and is accountable for governed, trustworthy AI outcomes.',
      motionIds: ['data_360_ai_readiness', 'agentforce_sales_automation'], products: ['Data 360', 'Agentforce'],
      personaSegment: 'Head of AI · VP Digital · Chief AI Officer',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'High',
      titles: 'Chief AI Officer · VP AI/ML · Head of Digital Transformation',
      responsibilities: 'AI roadmap, model governance, trust & safety, value realization.',
      fit: 'Funded AI program, board reporting on AI, existing data platform investment.',
      disqualifiers: 'AI in exploration only, no executive sponsor.',
      recommendedAgentUse: 'Lead with trusted-data-for-AI narrative; bridge to Agentforce motion.',
      sources: [
        S('Call recording', 'Roadmap review — Pyramid Construction', '"The board wants AI wins this year but legal won\u2019t sign off until the data is governed."', 'Mar 09, 2026', 'Gong · 38 min'),
        S('Website', 'Einstein Trust Layer overview', 'Trusted AI grounded in your customer data with built-in guardrails.', 'Mar 12, 2026', 'salesforce.example/products/trust-layer'),
      ] }),
    R({ id: 'pain_fragmented_data', category: 'Pain Point', value: 'Fragmented customer data',
      description: 'Customer data lives across disconnected apps, warehouses, and channels, blocking personalization and AI.',
      motionIds: ['data_360_ai_readiness', 'agentforce_sales_automation'], products: ['Data 360', 'Agentforce'],
      personaSegment: 'CDO · CIO · Marketing Ops', confidence: 'High', claimType: 'Stated', status: 'Approved', priority: 'High',
      whyMatters: 'Without a unified profile, AI is ungrounded and personalization breaks across channels.',
      capability: 'Zero-copy data unification and a real-time customer 360 profile.',
      valueProp: 'One trusted profile that powers every team, app, and AI agent.',
      outcome: 'Faster AI deployment, higher personalization lift, less duplicate tooling.',
      relatedPersona: 'Data Leader',
      recommendedAgentUse: 'Core wedge for Data 360 + Agentforce when an account shows AI or personalization signals.',
      sources: [
        S('Website', 'Customer data solution', 'Bring together fragmented customer data into a trusted profile for AI and personalization.', 'Mar 12, 2026', 'salesforce.example/solutions/customer-data'),
        S('Call recording', 'Discovery — Cloud Kicks', '"Every team has its own version of the customer. Marketing and service don\u2019t even match."', 'Feb 24, 2026', 'Gong · 51 min'),
        S('Email', 'Follow-up — Northern Trail', '"Confirmed: 9 source systems, no golden record. This is our #1 blocker for AI."', 'Mar 02, 2026', 'thread'),
      ] }),
    R({ id: 'pain_poor_activation', category: 'Pain Point', value: 'Poor data activation',
      description: 'Data is collected but rarely activated in real time where customer interactions happen.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'Marketing Ops · Data Leader',
      confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Insights stuck in a warehouse never reach the moment of action.',
      capability: 'Real-time activation into Flow, journeys, and agent actions.',
      valueProp: 'Turn data into action at the point of interaction.',
      outcome: 'Higher conversion and faster response on high-intent signals.',
      relatedPersona: 'Marketing Operations Leader',
      recommendedAgentUse: 'Pair with personalization or campaign-performance pains.',
      sources: [
        S('Website', 'Data activation page', 'Activate unified data in real time across journeys and agents.', 'Mar 12, 2026', 'salesforce.example/products/data-360/activation'),
      ] }),
    R({ id: 'pain_ungrounded_ai', category: 'Pain Point', value: 'Difficulty grounding AI in trusted data',
      description: 'AI initiatives stall because models lack governed, trustworthy customer context.',
      motionIds: ['data_360_ai_readiness', 'agentforce_sales_automation'], products: ['Data 360', 'Agentforce'],
      personaSegment: 'AI Transformation Leader · CDO', confidence: 'High', claimType: 'Stated', status: 'Needs Admin Review', priority: 'High',
      whyMatters: 'Ungrounded AI produces hallucinations and fails compliance review.',
      capability: 'Trust Layer + grounding on the unified customer profile.',
      valueProp: 'Deploy AI your legal and security teams will actually approve.',
      outcome: 'Shorter path from AI pilot to production.',
      relatedPersona: 'AI Transformation Leader',
      recommendedAgentUse: 'Lead messaging when AI-governance or trust concerns surface.',
      sources: [
        S('Call recording', 'Security review — Pyramid', '"Legal blocked the last pilot — no lineage, no guardrails. We can\u2019t ship that."', 'Mar 09, 2026', 'Gong · 27 min'),
        S('Website', 'Trusted AI page', 'Ground every AI interaction in trusted, permissioned customer data.', 'Mar 12, 2026', 'salesforce.example/products/trusted-ai'),
      ] }),
    R({ id: 'value_trusted_profiles', category: 'Value Proposition', value: 'Trusted customer profiles for AI',
      description: 'Unify and govern customer data so AI agents and teams act on trusted context.',
      motionIds: ['data_360_ai_readiness', 'agentforce_sales_automation'], products: ['Data 360', 'Agentforce'],
      personaSegment: 'CDO · CIO · AI Transformation Leader', confidence: 'High', claimType: 'Stated', status: 'Suggested', priority: 'High',
      whyMatters: 'A trusted profile is the prerequisite for safe, useful AI.',
      capability: 'Customer 360 + Trust Layer grounding.',
      valueProp: 'Ground AI in trusted customer data across Salesforce.',
      outcome: 'AI that is accurate, compliant, and adopted.',
      relatedPersona: 'Data Leader',
      recommendedAgentUse: 'Primary value prop for AI-readiness signals.',
      sources: [
        S('Website', 'Data 360 for AI', 'Ground AI in trusted customer data across Salesforce.', 'Mar 12, 2026', 'salesforce.example/products/data-360-ai'),
      ] }),
    R({ id: 'value_zero_copy', category: 'Value Proposition', value: 'Zero-copy data access',
      description: 'Access data where it lives — no costly duplication or brittle pipelines.',
      motionIds: ['data_360_ai_readiness', 'mulesoft_integration_modernization'], products: ['Data 360'],
      personaSegment: 'CIO · Enterprise Architect', confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Duplication drives cost, latency, and governance risk.',
      capability: 'Zero-copy integration with major warehouses and lakes.',
      valueProp: 'Unify without moving your data.',
      outcome: 'Lower storage cost, faster time-to-value.',
      relatedPersona: 'Enterprise Architect',
      recommendedAgentUse: 'Use when cost or data-movement objections arise.',
      sources: [
        S('Website', 'Zero-copy page', 'Connect to data where it lives with zero-copy access.', 'Mar 12, 2026', 'salesforce.example/products/zero-copy'),
      ] }),
    R({ id: 'sig_new_cdo', category: 'Signal Playbook', value: 'New CDO hired',
      description: 'A new data leader usually has a mandate to modernize architecture and prove AI readiness.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'CDO · VP Data',
      confidence: 'Medium', claimType: 'Inferred', status: 'Needs Admin Review', priority: 'High', ttlDays: 90,
      signalCategory: 'Leadership change', painHyp: 'Fragmented customer data',
      angle: 'AI readiness requires trusted data',
      recommendedAgentUse: 'Wake the agent when a target account hires a senior data leader; draft outreach around trusted data for AI.',
      sources: [
        S('Website', 'Thought-leadership blog', 'Data leaders are under pressure to prepare enterprise data for AI adoption.', 'Mar 12, 2026', 'salesforce.example/blog/data-leaders-ai-readiness'),
        S('CRM note', 'Signal — LinkedIn change', 'Detected new CDO appointment at target account; tagged for outreach.', 'Mar 10, 2026', 'Signal log'),
      ] }),
    R({ id: 'sig_public_ai', category: 'Signal Playbook', value: 'Public AI initiative announced',
      description: 'Public commitment to AI creates urgency and budget for a trusted data foundation.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360', 'Agentforce'], personaSegment: 'AI Transformation Leader · CIO',
      confidence: 'High', claimType: 'Inferred', status: 'Suggested', priority: 'High', ttlDays: 120,
      signalCategory: 'Strategic announcement', painHyp: 'Difficulty grounding AI in trusted data',
      angle: 'AI readiness requires trusted data',
      recommendedAgentUse: 'Reference the public initiative; offer a trusted-data readiness assessment.',
      sources: [
        S('Email', 'AE forward — press release', '"They announced a $40M AI program on the earnings call — perfect timing."', 'Mar 05, 2026', 'thread'),
      ] }),
    R({ id: 'sig_hiring_data_eng', category: 'Signal Playbook', value: 'Hiring data engineers at scale',
      description: 'A surge in data-engineering hiring signals platform investment and integration pain.',
      motionIds: ['data_360_ai_readiness', 'mulesoft_integration_modernization'], products: ['Data 360', 'MuleSoft'],
      personaSegment: 'VP Data · Enterprise Architect', confidence: 'Low', claimType: 'Inferred', status: 'Needs Admin Review', priority: 'Medium', ttlDays: 60,
      signalCategory: 'Hiring trend', painHyp: 'Poor data activation',
      angle: 'Spend engineering effort on outcomes, not plumbing',
      recommendedAgentUse: 'Low-confidence — confirm with a second signal before outreach.',
      sources: [
        S('CRM note', 'Signal — job postings', '12 open data-engineering roles detected; weak signal, needs corroboration.', 'Mar 08, 2026', 'Signal log'),
      ] }),
    R({ id: 'msg_ai_trusted_data', category: 'Messaging Angle', value: 'AI readiness requires trusted data',
      description: 'Frame trusted, unified data as the prerequisite for any successful AI program.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360', 'Agentforce'], personaSegment: 'CDO · CIO · AI Leader',
      confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      useWhen: 'Account shows AI, personalization, or data-modernization signals.',
      hook: '"Most AI programs stall on data, not models. What does trusted data look like for your team?"',
      avoid: 'Avoid implying AI replaces governance or that data work is one-and-done.',
      recommendedAgentUse: 'Approved opening angle for AI-readiness conversations.',
      sources: [
        S('Call recording', 'Win review — Cloud Kicks', '"The trusted-data framing is what unlocked the exec conversation for us."', 'Feb 20, 2026', 'Gong · 33 min'),
      ] }),
    R({ id: 'msg_no_data_no_ai', category: 'Messaging Angle', value: 'No data strategy, no AI strategy',
      description: 'Position data unification as the foundation rather than a parallel workstream.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'AI Transformation Leader',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'Medium',
      useWhen: 'Prospect treats AI and data as separate initiatives.',
      hook: '"Your AI roadmap is only as good as the data underneath it."',
      avoid: 'Don\u2019t disparage the customer\u2019s existing investments.',
      recommendedAgentUse: 'Secondary angle when AI strategy is ahead of data strategy.',
      sources: [
        S('Website', 'AI readiness guide', 'A trusted data foundation is the first step to enterprise AI.', 'Mar 12, 2026', 'salesforce.example/guides/ai-readiness'),
      ] }),
    R({ id: 'proof_saks', category: 'Case Study', value: 'Saks personalization story',
      description: 'Retail case study showing personalization powered by unified customer data and AI.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360', 'Agentforce'], personaSegment: 'Retail CMO · CIO · CX Leader',
      confidence: 'Medium', claimType: 'Stated', status: 'Needs Admin Review', priority: 'Medium',
      proofType: 'Case Study', useCase: 'Retail personalization, unified customer data', safeForOutreach: true,
      recommendedAgentUse: 'Use as proof for retail personalization and unified-data messaging.',
      sources: [
        S('Website', 'Saks customer story', 'Saks uses unified customer data and AI to personalize luxury shopping experiences.', 'Mar 12, 2026', 'salesforce.example/customers/saks'),
      ] }),
    R({ id: 'proof_trust_layer', category: 'Compliance / Security', value: 'Einstein Trust Layer',
      description: 'Trusted-AI guardrail providing grounding, masking, and zero-retention controls.',
      motionIds: ['data_360_ai_readiness', 'agentforce_sales_automation'], products: ['Agentforce', 'Data 360'],
      personaSegment: 'CISO · AI Transformation Leader', confidence: 'High', claimType: 'Stated', status: 'Locked', priority: 'High',
      proofType: 'Compliance / Security', useCase: 'Address AI trust, privacy, and governance objections', safeForOutreach: true,
      recommendedAgentUse: 'Cite when security or governance concerns arise; do not overstate scope.',
      sources: [
        S('Website', 'Trust Layer page', 'Built-in guardrails: data masking, zero retention, toxicity filtering, audit trail.', 'Mar 12, 2026', 'salesforce.example/products/trust-layer'),
      ] }),

    // ═══════════════ SALES CLOUD — REP PRODUCTIVITY ═══════════════
    R({ id: 'p_sales_leader', category: 'Buyer Persona', value: 'Sales Leader',
      description: 'Owns pipeline generation, seller productivity, forecasting, and revenue execution.',
      motionIds: ['sales_cloud_rep_productivity', 'agentforce_sales_automation'], products: ['Sales Cloud', 'Agentforce Sales'],
      personaSegment: 'CRO · VP Sales · Sales Operations', confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      titles: 'CRO · VP Sales · RVP · Head of Revenue Operations',
      responsibilities: 'Pipeline coverage, forecast accuracy, rep ramp, productivity, quota attainment.',
      fit: 'Large quota-carrying team, CRM hygiene problems, ramp/attainment pressure.',
      disqualifiers: 'Tiny sales team, no CRM, transactional self-serve only.',
      recommendedAgentUse: 'Target sales executives and ops leaders for productivity messaging.',
      sources: [
        S('Website', 'Sales Cloud page', 'Help sellers sell faster with AI, automation, and connected customer data.', 'Mar 12, 2026', 'salesforce.example/products/sales-cloud'),
        S('Call recording', 'Discovery — Dickenson plc (VP Sales)', '"Reps spend Friday afternoons updating Salesforce instead of selling. It\u2019s killing us."', 'Mar 01, 2026', 'Gong · 44 min'),
      ] }),
    R({ id: 'p_revops', category: 'Buyer Persona', value: 'RevOps Leader',
      description: 'Designs the selling system: process, tooling, data hygiene, and automation.',
      motionIds: ['sales_cloud_rep_productivity'], products: ['Sales Cloud'], personaSegment: 'VP RevOps · Sales Ops Director',
      confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      titles: 'VP Revenue Operations · Director Sales Ops · Salesforce Admin Lead',
      responsibilities: 'CRM configuration, automation, data quality, enablement tooling, reporting.',
      fit: 'Dedicated ops function, complex sales process, multiple point tools.',
      disqualifiers: 'No ops owner, fully manual process.',
      recommendedAgentUse: 'Engage as the technical champion for automation and data hygiene.',
      sources: [
        S('Email', 'Inbound — Dickenson RevOps', '"We have 14 tools bolted onto Salesforce. I want to consolidate and automate the busywork."', 'Mar 03, 2026', 'inbound@'),
      ] }),
    R({ id: 'pain_manual_admin', category: 'Pain Point', value: 'Manual sales administration',
      description: 'Reps spend too much time updating CRM, prepping follow-ups, and juggling systems.',
      motionIds: ['sales_cloud_rep_productivity', 'agentforce_sales_automation'], products: ['Sales Cloud', 'Agentforce Sales'],
      personaSegment: 'Sales Leader · RevOps · AE', confidence: 'High', claimType: 'Stated', status: 'Approved', priority: 'High',
      whyMatters: 'Every hour on admin is an hour not selling; data quality also suffers.',
      capability: 'AI-drafted updates, auto-logged activity, next-best-action.',
      valueProp: 'Keep reps focused on selling, not data entry.',
      outcome: 'More selling time, cleaner pipeline, better forecasts.',
      relatedPersona: 'Sales Leader',
      recommendedAgentUse: 'Core wedge for rep-productivity conversations.',
      sources: [
        S('Website', 'Sales automation page', 'Automate seller workflows and keep reps focused on selling.', 'Mar 12, 2026', 'salesforce.example/products/sales-cloud/automation'),
        S('Call recording', 'Discovery — Dickenson plc', '"My AEs say CRM updates eat 6+ hours a week. I believe them."', 'Mar 01, 2026', 'Gong · 44 min'),
        S('CRM note', 'QBR — Express Logistics', 'Forecast misses traced to stale opportunity data; reps not updating in time.', 'Feb 26, 2026', 'Account activity'),
      ] }),
    R({ id: 'pain_slow_ramp', category: 'Pain Point', value: 'Slow new-rep ramp',
      description: 'New reps take too long to reach quota because playbooks and context live in people\u2019s heads.',
      motionIds: ['sales_cloud_rep_productivity'], products: ['Sales Cloud', 'Agentforce Sales'], personaSegment: 'Sales Leader · Enablement',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Long ramp delays revenue and raises cost-of-sale.',
      capability: 'Guided selling, in-context coaching, AI call summaries.',
      valueProp: 'Ramp reps in weeks, not quarters.',
      outcome: 'Faster time-to-first-deal, more consistent execution.',
      relatedPersona: 'Sales Leader',
      recommendedAgentUse: 'Use when account mentions hiring or ramp pressure.',
      sources: [
        S('Website', 'Sales enablement page', 'Guide reps with in-context coaching and AI-generated summaries.', 'Mar 12, 2026', 'salesforce.example/products/enablement'),
      ] }),
    R({ id: 'pain_forecast_accuracy', category: 'Pain Point', value: 'Poor forecast accuracy',
      description: 'Leaders can\u2019t trust the forecast because pipeline data is stale and inconsistent.',
      motionIds: ['sales_cloud_rep_productivity'], products: ['Sales Cloud'], personaSegment: 'CRO · RevOps',
      confidence: 'Medium', claimType: 'Stated', status: 'Needs Admin Review', priority: 'High',
      whyMatters: 'Bad forecasts erode board trust and lead to misallocated resources.',
      capability: 'AI forecasting grounded in real activity data.',
      valueProp: 'A forecast leadership can actually trust.',
      outcome: 'Tighter forecast variance, fewer surprises.',
      relatedPersona: 'Sales Leader',
      recommendedAgentUse: 'Pair with manual-admin pain; forecast pain is a symptom of bad data.',
      sources: [
        S('Call recording', 'EBR — Express Logistics (CRO)', '"I can\u2019t walk into the board with a forecast I don\u2019t believe."', 'Feb 18, 2026', 'Gong · 29 min'),
      ] }),
    R({ id: 'msg_less_admin', category: 'Messaging Angle', value: 'Less admin, more selling',
      description: 'Position AI/automation as removing operating work around the seller, not replacing the seller.',
      motionIds: ['sales_cloud_rep_productivity', 'agentforce_sales_automation'], products: ['Sales Cloud', 'Agentforce Sales'],
      personaSegment: 'CRO · VP Sales · RevOps', confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      useWhen: 'Productivity, CRM-hygiene, or attainment concerns surface.',
      hook: '"What if your reps got 5 hours back a week — and the CRM stayed current automatically?"',
      avoid: 'Avoid implying the agent replaces reps or owns the customer relationship.',
      recommendedAgentUse: 'Approved opening angle for productivity campaigns.',
      sources: [
        S('Website', 'Agentforce Sales page', 'AI agents handle repetitive work and surface next best actions.', 'Mar 12, 2026', 'salesforce.example/products/agentforce-sales'),
      ] }),
    R({ id: 'sig_sales_productivity_initiative', category: 'Signal Playbook', value: 'New sales-productivity initiative',
      description: 'A publicly stated productivity or efficiency program signals budget and urgency.',
      motionIds: ['sales_cloud_rep_productivity'], products: ['Sales Cloud', 'Agentforce Sales'], personaSegment: 'CRO · RevOps',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'High', ttlDays: 90,
      signalCategory: 'Strategic announcement', painHyp: 'Manual sales administration',
      angle: 'Less admin, more selling',
      recommendedAgentUse: 'Wake agent on efficiency/productivity initiatives; lead with time-back narrative.',
      sources: [
        S('Email', 'AE note — earnings call', '"CFO called out a sales-efficiency push for the year. Good wedge."', 'Mar 04, 2026', 'thread'),
      ] }),
    R({ id: 'proof_ntl_sales', category: 'Case Study', value: 'Express Logistics productivity story',
      description: 'Sample B2B case study showing seller time-savings from automation.',
      motionIds: ['sales_cloud_rep_productivity'], products: ['Sales Cloud', 'Agentforce Sales'], personaSegment: 'CRO · RevOps',
      confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      proofType: 'Case Study', useCase: 'Seller time-savings, CRM hygiene', safeForOutreach: true,
      recommendedAgentUse: 'Proof for productivity and automation messaging.',
      sources: [
        S('Website', 'Customer story', 'Express Logistics gave reps hours back each week with automated CRM updates.', 'Mar 12, 2026', 'salesforce.example/customers/express-logistics'),
      ] }),

    // ═══════════════ AGENTFORCE — SALES AGENT AUTOMATION ═══════════════
    R({ id: 'p_sales_leader_af', category: 'Buyer Persona', value: 'Sales Leader (AI-forward)',
      description: 'Revenue leader actively exploring AI agents to scale selling capacity.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce', 'Sales Cloud'], personaSegment: 'CRO · VP Sales · Chief Revenue Officer',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'High',
      titles: 'CRO · VP Sales · Head of Sales Innovation',
      responsibilities: 'Revenue capacity, AI adoption in sales, pipeline scale.',
      fit: 'Existing Salesforce footprint, AI mandate, capacity constraints.',
      disqualifiers: 'No CRM data foundation, AI-averse culture.',
      recommendedAgentUse: 'Engage AI-curious revenue leaders; require a data-foundation check first.',
      sources: [
        S('Call recording', 'Exec briefing — Grand Hotels (CRO)', '"Can an agent actually book meetings and prep my reps, not just summarize calls?"', 'Mar 07, 2026', 'Gong · 36 min'),
      ] }),
    R({ id: 'pain_pipeline_capacity', category: 'Pain Point', value: 'Limited pipeline-generation capacity',
      description: 'Teams can\u2019t scale top-of-funnel work without adding headcount.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce', 'Sales Cloud'], personaSegment: 'CRO · Sales Dev Leader',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'High',
      whyMatters: 'Pipeline coverage gaps directly threaten attainment.',
      capability: 'Autonomous prospecting and follow-up agents within guardrails.',
      valueProp: 'Scale pipeline work without scaling headcount.',
      outcome: 'More qualified pipeline per rep.',
      relatedPersona: 'Sales Leader (AI-forward)',
      recommendedAgentUse: 'Use when capacity or coverage gaps are stated.',
      sources: [
        S('Website', 'Agentforce SDR page', 'Agentforce SDR engages and qualifies inbound around the clock.', 'Mar 12, 2026', 'salesforce.example/products/agentforce-sdr'),
      ] }),
    R({ id: 'value_agent_capacity', category: 'Value Proposition', value: 'Always-on selling capacity',
      description: 'AI agents extend the team\u2019s capacity for follow-up, research, and qualification.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce'], personaSegment: 'CRO · RevOps',
      confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Capacity is the constraint on growth for most teams.',
      capability: 'Configurable agents with human-in-the-loop approval.',
      valueProp: 'Add selling capacity without adding risk.',
      outcome: 'Faster follow-up, higher conversion on inbound.',
      relatedPersona: 'Sales Leader (AI-forward)',
      recommendedAgentUse: 'Lead value prop for capacity-constrained teams.',
      sources: [
        S('Website', 'Agentforce overview', 'Deploy AI agents that work within your guardrails and approvals.', 'Mar 12, 2026', 'salesforce.example/products/agentforce'),
      ] }),
    R({ id: 'sig_ai_pilot', category: 'Signal Playbook', value: 'Stated AI agent pilot',
      description: 'Account publicly piloting AI agents is in-market for governed, CRM-grounded automation.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce'], personaSegment: 'CRO · AI Leader',
      confidence: 'Medium', claimType: 'Inferred', status: 'Needs Admin Review', priority: 'High', ttlDays: 75,
      signalCategory: 'Strategic announcement', painHyp: 'Limited pipeline-generation capacity',
      angle: 'Agents that act inside your guardrails',
      recommendedAgentUse: 'Differentiate on trust + CRM grounding vs. point AI tools.',
      sources: [
        S('CRM note', 'Signal — competitor pilot', 'Account piloting a point AI SDR tool; opening to reposition on trust + data.', 'Mar 09, 2026', 'Signal log'),
      ] }),
    R({ id: 'msg_agents_guardrails', category: 'Messaging Angle', value: 'Agents that act inside your guardrails',
      description: 'Emphasize permissioned, auditable agent actions with human approval.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce'], personaSegment: 'CRO · CISO · AI Leader',
      confidence: 'High', claimType: 'Inferred', status: 'Suggested', priority: 'High',
      useWhen: 'Trust, control, or autonomy concerns surface.',
      hook: '"Your agent only does what you permit — with a full audit trail. Want to see the guardrails?"',
      avoid: 'Never imply the agent acts autonomously without oversight.',
      recommendedAgentUse: 'Lead angle when trust is the objection.',
      sources: [
        S('Website', 'Agentforce trust page', 'Agents operate within customer-defined permissions and human approval workflows.', 'Mar 12, 2026', 'salesforce.example/trust/agentforce-guidelines'),
      ] }),
    R({ id: 'guardrail_no_replace', category: 'Messaging Guardrail', value: 'Do not claim the agent fully replaces reps',
      description: 'Messaging should say the agent assists, drafts, recommends, and tees up actions — not that it negotiates, prices, or owns the relationship autonomously.',
      motionIds: ['agentforce_sales_automation', 'sales_cloud_rep_productivity'], products: ['Agentforce', 'Sales Cloud'],
      personaSegment: 'All customer-facing messaging', confidence: 'High', claimType: 'Stated', status: 'Locked', priority: 'High',
      proofType: 'Messaging Guardrail', useCase: 'Prevent overpromising agent autonomy', safeForOutreach: false,
      recommendedAgentUse: 'Locked guardrail — agent must never imply full rep replacement.',
      sources: [
        S('Website', 'Agentforce guidelines', 'AI agents operate within customer-defined permissions and human approval workflows.', 'Mar 12, 2026', 'salesforce.example/trust/agentforce-guidelines'),
        S('Email', 'Legal — messaging review', '"Approved language must say \u2018assists reps,\u2019 never \u2018replaces reps.\u2019 Lock this."', 'Mar 06, 2026', 'legal review'),
      ] }),
    R({ id: 'guardrail_no_pricing', category: 'Messaging Guardrail', value: 'Do not claim autonomous pricing or legal decisions',
      description: 'The agent must not be described as making pricing, contractual, or legal decisions on its own.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce'], personaSegment: 'All customer-facing messaging',
      confidence: 'High', claimType: 'Stated', status: 'Locked', priority: 'High',
      proofType: 'Messaging Guardrail', useCase: 'Avoid regulated-decision claims', safeForOutreach: false,
      recommendedAgentUse: 'Locked — never imply autonomous pricing or legal authority.',
      sources: [
        S('Website', 'Trust guidelines', 'High-stakes decisions require human review and approval.', 'Mar 12, 2026', 'salesforce.example/trust/agentforce-guidelines'),
      ] }),
    R({ id: 'comp_point_ai', category: 'Competitor / Alternative', value: 'Point AI SDR tools',
      description: 'Standalone AI prospecting tools that lack CRM grounding and enterprise guardrails.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce'], personaSegment: 'CRO · RevOps',
      confidence: 'Medium', claimType: 'Inferred', status: 'Needs Admin Review', priority: 'Medium',
      proofType: 'Competitor / Alternative', useCase: 'Differentiate on trust + native CRM data', safeForOutreach: false,
      recommendedAgentUse: 'Internal positioning — differentiate, do not disparage by name.',
      sources: [
        S('Call recording', 'Competitive — Grand Hotels', '"We tried a bolt-on AI SDR; it hallucinated and our data was a mess afterward."', 'Mar 07, 2026', 'Gong · 36 min'),
      ] }),

    // ═══════════════ SERVICE CLOUD — CONTACT CENTER MODERNIZATION ═══════════════
    R({ id: 'p_service_leader', category: 'Buyer Persona', value: 'Service Leader',
      description: 'Owns service operations, contact-center performance, case resolution, and CX.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'VP Support · VP CX · Contact Center Leader',
      confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      titles: 'VP Customer Support · VP Customer Experience · Director Contact Center',
      responsibilities: 'CSAT, resolution time, deflection, agent productivity, cost-to-serve.',
      fit: 'High-volume contact center, cost pressure, CX mandate.',
      disqualifiers: 'No support org, fully self-serve product.',
      recommendedAgentUse: 'Target for support transformation and contact-center modernization.',
      sources: [
        S('Website', 'Service Cloud page', 'Improve service productivity and resolve issues faster with AI-assisted workflows.', 'Mar 12, 2026', 'salesforce.example/products/service-cloud'),
        S('Call recording', 'Discovery — Grand Hotels (VP CX)', '"Handle time is up, CSAT is down, and we can\u2019t hire our way out of it."', 'Mar 02, 2026', 'Gong · 41 min'),
      ] }),
    R({ id: 'p_cc_ops', category: 'Buyer Persona', value: 'Contact Center Ops Manager',
      description: 'Runs day-to-day staffing, queues, knowledge, and agent enablement.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud'], personaSegment: 'Contact Center Ops · WFM Lead',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'Medium',
      titles: 'Contact Center Operations Manager · Workforce Management Lead',
      responsibilities: 'Staffing, queue routing, knowledge base, QA, agent tooling.',
      fit: 'Multi-channel center, knowledge gaps, high attrition.',
      disqualifiers: 'Tiny support team, no formal ops.',
      recommendedAgentUse: 'Technical champion for deflection and agent-assist features.',
      sources: [
        S('Email', 'Inbound — Grand Hotels ops', '"Our agents can\u2019t find answers fast enough. Knowledge is scattered everywhere."', 'Mar 04, 2026', 'inbound@'),
      ] }),
    R({ id: 'pain_slow_resolution', category: 'Pain Point', value: 'Slow case resolution',
      description: 'Support teams resolve issues slowly when agents lack context, knowledge, or automation.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'Service Leader · CC Ops',
      confidence: 'High', claimType: 'Stated', status: 'Approved', priority: 'High',
      whyMatters: 'Slow resolution hurts CSAT and drives up cost-to-serve.',
      capability: 'AI answers, next-best-action, connected customer context.',
      valueProp: 'Resolve more, faster, with AI-assisted service.',
      outcome: 'Lower handle time, higher CSAT, better deflection.',
      relatedPersona: 'Service Leader',
      recommendedAgentUse: 'Core wedge for contact-center modernization signals.',
      sources: [
        S('Website', 'AI service page', 'Give service teams AI-powered answers and connected customer context.', 'Mar 12, 2026', 'salesforce.example/products/service-cloud/ai-service'),
        S('Call recording', 'Discovery — Grand Hotels', '"Average handle time is 14 minutes. Half of that is agents hunting for the answer."', 'Mar 02, 2026', 'Gong · 41 min'),
      ] }),
    R({ id: 'pain_cost_to_serve', category: 'Pain Point', value: 'Rising cost-to-serve',
      description: 'Support costs grow faster than revenue as volume and complexity increase.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'VP Support · CFO',
      confidence: 'Medium', claimType: 'Stated', status: 'Needs Admin Review', priority: 'High',
      whyMatters: 'Cost-to-serve pressure puts service budgets under the microscope.',
      capability: 'Self-service deflection + agent-assist automation.',
      valueProp: 'Serve more customers at lower cost per case.',
      outcome: 'Higher deflection, reduced cost per contact.',
      relatedPersona: 'Service Leader',
      recommendedAgentUse: 'Use when cost-cutting or efficiency mandates are present.',
      sources: [
        S('CRM note', 'Account — Grand Hotels', 'CFO mandated 15% reduction in cost-to-serve this fiscal year.', 'Feb 27, 2026', 'Account activity'),
      ] }),
    R({ id: 'msg_resolve_more_ai', category: 'Messaging Angle', value: 'Resolve more with AI-assisted service',
      description: 'Position AI as augmenting agents to resolve faster, not replacing the human touch.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'VP Support · CC Ops',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'Medium',
      useWhen: 'Handle-time, CSAT, or deflection concerns surface.',
      hook: '"What if every agent had the best answer at their fingertips on every case?"',
      avoid: 'Avoid implying full automation of complex or sensitive cases.',
      recommendedAgentUse: 'Opening angle for service modernization.',
      sources: [
        S('Website', 'Agentforce Service page', 'AI-assisted service resolves common cases and supports agents on complex ones.', 'Mar 12, 2026', 'salesforce.example/products/agentforce-service'),
      ] }),
    R({ id: 'sig_cost_cutting', category: 'Signal Playbook', value: 'Contact-center cost-cutting mandate',
      description: 'A stated cost-reduction or efficiency mandate signals urgency for deflection and automation.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'VP Support · CFO',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'High', ttlDays: 90,
      signalCategory: 'Strategic announcement', painHyp: 'Rising cost-to-serve',
      angle: 'Resolve more with AI-assisted service',
      recommendedAgentUse: 'Wake agent on service cost mandates; lead with deflection ROI.',
      sources: [
        S('Email', 'AE note — earnings', '"They flagged contact-center efficiency as a cost lever for the year."', 'Mar 05, 2026', 'thread'),
      ] }),
    R({ id: 'proof_ntl_service', category: 'Case Study', value: 'Northern Trail Outfitters service automation',
      description: 'Sample case study showing deflection and faster resolution from AI-assisted service.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'VP Support · CX Leader',
      confidence: 'Medium', claimType: 'Stated', status: 'Needs Admin Review', priority: 'Medium',
      proofType: 'Case Study', useCase: 'Deflection, faster resolution', safeForOutreach: true,
      recommendedAgentUse: 'Proof for service modernization and deflection messaging.',
      sources: [
        S('Website', 'NTO customer story', 'Northern Trail Outfitters cut handle time with AI-assisted service.', 'Mar 12, 2026', 'salesforce.example/customers/nto'),
      ] }),

    // ═══════════════ MULESOFT — INTEGRATION MODERNIZATION ═══════════════
    R({ id: 'p_enterprise_architect', category: 'Buyer Persona', value: 'Enterprise Architect',
      description: 'Designs integration strategy, API governance, and system-of-record architecture.',
      motionIds: ['mulesoft_integration_modernization'], products: ['MuleSoft'], personaSegment: 'Chief Architect · VP Integration · Platform Lead',
      confidence: 'High', claimType: 'Inferred', status: 'Approved', priority: 'High',
      titles: 'Chief Enterprise Architect · VP Integration · Head of Platform Engineering',
      responsibilities: 'Integration strategy, API lifecycle, reuse, governance, technical debt.',
      fit: 'Many systems, custom point-to-point integrations, M&A history.',
      disqualifiers: 'Simple stack, no integration backlog.',
      recommendedAgentUse: 'Target architects on reuse, governance, and consolidation.',
      sources: [
        S('Website', 'MuleSoft page', 'Connect any system with reusable APIs and integration.', 'Mar 12, 2026', 'salesforce.example/products/mulesoft'),
        S('Call recording', 'Discovery — Pyramid (Chief Architect)', '"We have 200+ point-to-point integrations. Every change breaks three things."', 'Mar 03, 2026', 'Gong · 47 min'),
      ] }),
    R({ id: 'pain_disconnected_systems', category: 'Pain Point', value: 'Disconnected systems after M&A',
      description: 'Acquisitions leave overlapping systems and broken data flows that slow the business.',
      motionIds: ['mulesoft_integration_modernization', 'data_360_ai_readiness'], products: ['MuleSoft', 'Data 360'],
      personaSegment: 'CIO · Enterprise Architect', confidence: 'High', claimType: 'Stated', status: 'Approved', priority: 'High',
      whyMatters: 'Disconnected systems block synergy capture and create data chaos.',
      capability: 'Reusable APIs + integration to unify systems and data.',
      valueProp: 'Connect acquired systems fast — without rip-and-replace.',
      outcome: 'Faster integration, realized M&A synergies.',
      relatedPersona: 'Enterprise Architect',
      recommendedAgentUse: 'Core wedge on M&A and consolidation signals.',
      sources: [
        S('Website', 'Integration modernization', 'Connect data and systems across the enterprise to create integrated experiences.', 'Mar 12, 2026', 'salesforce.example/solutions/integration-modernization'),
        S('CRM note', 'Account — Pyramid', 'Closed two acquisitions in 18 months; integration backlog is the top IT risk.', 'Feb 25, 2026', 'Account activity'),
      ] }),
    R({ id: 'pain_integration_backlog', category: 'Pain Point', value: 'Integration backlog slows delivery',
      description: 'Every new initiative waits on custom integration work, delaying time-to-value.',
      motionIds: ['mulesoft_integration_modernization'], products: ['MuleSoft'], personaSegment: 'Enterprise Architect · CIO',
      confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Integration bottlenecks throttle every digital initiative, including AI.',
      capability: 'Reusable API building blocks and automation.',
      valueProp: 'Ship integrations in days by reusing what you\u2019ve built.',
      outcome: 'Faster delivery, less custom code.',
      relatedPersona: 'Enterprise Architect',
      recommendedAgentUse: 'Use when delivery speed or backlog is the pain.',
      sources: [
        S('Website', 'API reuse page', 'Reuse APIs to accelerate every new project.', 'Mar 12, 2026', 'salesforce.example/products/mulesoft/api-reuse'),
      ] }),
    R({ id: 'value_reusable_apis', category: 'Value Proposition', value: 'Reusable APIs accelerate everything',
      description: 'Composable, reusable APIs turn integration from a cost center into an accelerant.',
      motionIds: ['mulesoft_integration_modernization'], products: ['MuleSoft'], personaSegment: 'Enterprise Architect',
      confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Reuse compounds — each API makes the next project faster.',
      capability: 'API design, management, and reuse across the org.',
      valueProp: 'Build once, reuse everywhere.',
      outcome: 'Lower integration cost, faster delivery.',
      relatedPersona: 'Enterprise Architect',
      recommendedAgentUse: 'Lead value prop for architecture-led conversations.',
      sources: [
        S('Website', 'MuleSoft value page', 'Composable, reusable APIs accelerate every initiative.', 'Mar 12, 2026', 'salesforce.example/products/mulesoft/value'),
      ] }),
    R({ id: 'sig_ma_event', category: 'Signal Playbook', value: 'M&A event',
      description: 'Mergers and acquisitions create urgency around integration, data consolidation, and standardization.',
      motionIds: ['mulesoft_integration_modernization', 'data_360_ai_readiness'], products: ['MuleSoft', 'Data 360'],
      personaSegment: 'CIO · Enterprise Architect · VP Data', confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'High', ttlDays: 120,
      signalCategory: 'Corporate event', painHyp: 'Disconnected systems after M&A',
      angle: 'Connect acquired systems without rip-and-replace',
      recommendedAgentUse: 'Wake agent on M&A news; draft messaging around integration and data consolidation.',
      sources: [
        S('Email', 'AE forward — M&A news', '"They just closed an acquisition — integration pain incoming. Reach out now."', 'Mar 06, 2026', 'thread'),
        S('CRM note', 'Signal — news monitor', 'Acquisition announced; flagged for integration-modernization outreach.', 'Mar 06, 2026', 'Signal log'),
      ] }),
    R({ id: 'sig_stack_consolidation', category: 'Signal Playbook', value: 'Tech-stack consolidation program',
      description: 'A stated consolidation or vendor-rationalization program signals integration and platform spend.',
      motionIds: ['mulesoft_integration_modernization'], products: ['MuleSoft', 'Data 360'], personaSegment: 'CIO · Enterprise Architect',
      confidence: 'Low', claimType: 'Inferred', status: 'Needs Admin Review', priority: 'Medium', ttlDays: 90,
      signalCategory: 'Strategic announcement', painHyp: 'Integration backlog slows delivery',
      angle: 'Reusable APIs accelerate everything',
      recommendedAgentUse: 'Low-confidence — confirm scope before outreach.',
      sources: [
        S('CRM note', 'Signal — IT strategy memo', 'Mentioned vendor consolidation; weak signal, needs a second source.', 'Mar 08, 2026', 'Signal log'),
      ] }),
    R({ id: 'proof_integration_pattern', category: 'Integration', value: 'Salesforce + MuleSoft + Data 360 pattern',
      description: 'Reference architecture connecting systems via MuleSoft and unifying data in Data 360.',
      motionIds: ['mulesoft_integration_modernization', 'data_360_ai_readiness'], products: ['MuleSoft', 'Data 360'],
      personaSegment: 'Enterprise Architect · CIO', confidence: 'Medium', claimType: 'Stated', status: 'Suggested', priority: 'Medium',
      proofType: 'Integration', useCase: 'Architecture proof for connect-then-unify story', safeForOutreach: true,
      recommendedAgentUse: 'Share with technical buyers to validate the end-to-end pattern.',
      sources: [
        S('Website', 'Reference architecture', 'Connect with MuleSoft, unify with Data 360, act with Agentforce.', 'Mar 12, 2026', 'salesforce.example/architecture/connect-unify-act'),
      ] }),
  ];

  // Duplicate candidate pair flag (for merge demo)
  // pain_fragmented_data <-> a near-duplicate suggested elsewhere
  rows.push(
    R({ id: 'pain_disconnected_profiles', category: 'Pain Point', value: 'Disconnected customer profiles',
      description: 'Customer profiles are inconsistent across systems, so no team sees the same customer.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'CDO · Marketing Ops',
      confidence: 'Medium', claimType: 'Inferred', status: 'Suggested', priority: 'Medium',
      whyMatters: 'Inconsistent profiles undermine trust in data and AI.',
      capability: 'Identity resolution into a single golden profile.',
      valueProp: 'One consistent profile for every team.',
      outcome: 'Trusted, consistent customer view.',
      relatedPersona: 'Data Leader',
      recommendedAgentUse: 'Likely a duplicate of "Fragmented customer data" — review for merge.',
      duplicateOf: 'pain_fragmented_data',
      sources: [
        S('Website', 'Identity resolution page', 'Resolve identities into a single trusted customer profile.', 'Mar 12, 2026', 'salesforce.example/products/identity-resolution'),
      ] })
  );

  window.GTM_DATA = {
    customer: 'Salesforce.com',
    extractedAt: 'Mar 12, 2026, 9:42 AM',
    motions,
    rows,
  };
})();
