// data2.js — persona enrichment + Ideal Company Profile data.
// Loads after data.js; mutates window.GTM_DATA.
(function () {
  const D = window.GTM_DATA;

  // Extraction provenance shown in the page header
  D.meta = {
    callsAnalyzed: '1,038',
    emailsAnalyzed: '4,210',
    pagesAnalyzed: '312',
    dealsAnalyzed: '47',
  };

  // ── Persona enrichment ─────────────────────────────────────────────────
  // What a persona looks like after mapping ~1,000 sales calls.
  const personas = {
    p_data_leader: {
      buyingRole: 'Economic buyer', reportsTo: 'CIO or CEO', callMentions: 214,
      caresAbout: ['AI readiness of enterprise data', 'Governance, lineage, and access control', 'Consolidating duplicate data tooling', 'Proving business value of the data platform'],
      kpis: ['Data quality score', 'Time-to-data for new use cases', 'Platform cost per workload', '% of AI projects unblocked by data'],
      objections: ['\u201CWe already have a lakehouse \u2014 why another platform?\u201D', '\u201CZero-copy sounds like lock-in by another name.\u201D', 'Governance of activated data outside the warehouse'],
      quote: '\u201CMy mandate this year is getting our data AI-ready \u2014 right now it\u2019s scattered across nine systems.\u201D',
      quoteSource: 'Discovery call \u2014 Northern Trail Outfitters, Feb 2026' },
    p_cio: {
      buyingRole: 'Economic buyer', reportsTo: 'CEO', callMentions: 167,
      caresAbout: ['Vendor consolidation and run-rate cost', 'Security and compliance posture', 'Board-level AI pressure', 'Platform simplification'],
      kpis: ['Run-rate IT cost', 'Audit findings', 'Time-to-deliver on business requests'],
      objections: ['\u201CHow does this reduce my vendor count rather than add to it?\u201D', 'Security review timelines', 'Fit with existing identity and governance stack'],
      quote: '\u201CWe need to rationalize the stack before we scale AI.\u201D',
      quoteSource: 'Inbound email \u2014 Acme Corp CIO, Mar 2026' },
    p_marketing_ops: {
      buyingRole: 'Champion', reportsTo: 'CMO', callMentions: 96,
      caresAbout: ['Audience activation speed', 'Identity resolution accuracy', 'Attribution across channels'],
      kpis: ['Segment build time', 'Identity match rate', 'Campaign conversion lift'],
      objections: ['\u201COur CDP already does this.\u201D', 'Implementation lift on a thin team'],
      quote: '\u201CIt takes us three weeks to build a segment that should take an afternoon.\u201D',
      quoteSource: 'Discovery call \u2014 retail prospect, Jan 2026' },
    p_ai_transformation: {
      buyingRole: 'Sponsor / influencer', reportsTo: 'CEO or CIO', callMentions: 142,
      caresAbout: ['Shipping AI wins the board can see', 'Model governance and legal sign-off', 'Grounding AI in trusted data'],
      kpis: ['AI pilots reaching production', 'Time-to-approval for AI use cases'],
      objections: ['\u201CWhy can\u2019t we just fine-tune on our warehouse data?\u201D', 'Hallucination and compliance risk'],
      quote: '\u201CThe board wants AI wins this year but legal won\u2019t sign off until the data is governed.\u201D',
      quoteSource: 'Roadmap review \u2014 Pyramid Construction, Mar 2026' },
    p_sales_leader: {
      buyingRole: 'Economic buyer', reportsTo: 'CEO', callMentions: 233,
      caresAbout: ['Forecast accuracy', 'Selling time per rep', 'Pipeline coverage', 'New-rep ramp'],
      kpis: ['Quota attainment', 'Forecast variance', 'Selling hours per rep per week'],
      objections: ['\u201CMy reps won\u2019t adopt another tool.\u201D', '\u201CWe tried automation once; data quality got worse.\u201D'],
      quote: '\u201CReps spend Friday afternoons updating Salesforce instead of selling.\u201D',
      quoteSource: 'Discovery call \u2014 Dickenson plc, Mar 2026' },
    p_revops: {
      buyingRole: 'Technical evaluator / champion', reportsTo: 'CRO', callMentions: 118,
      caresAbout: ['Tool consolidation', 'CRM data hygiene', 'Automating low-value process work'],
      kpis: ['CRM field completeness', 'Tool spend', 'Cycle time per stage'],
      objections: ['Migration effort from the current stack', 'Admin team capacity'],
      quote: '\u201CWe have 14 tools bolted onto Salesforce. I want to consolidate and automate the busywork.\u201D',
      quoteSource: 'Inbound email \u2014 Dickenson plc RevOps, Mar 2026' },
    p_sales_leader_af: {
      buyingRole: 'Economic buyer', reportsTo: 'CEO', callMentions: 87,
      caresAbout: ['Scaling capacity without headcount', 'Guardrails and auditability', 'Speed-to-lead on inbound'],
      kpis: ['Speed-to-lead', 'Meetings booked per rep', 'Cost per qualified opportunity'],
      objections: ['\u201CWill it embarrass us in front of customers?\u201D', 'Brand and voice control', 'Legal review of automated outreach'],
      quote: '\u201CCan an agent actually book meetings and prep my reps, not just summarize calls?\u201D',
      quoteSource: 'Exec briefing \u2014 Grand Hotels & Resorts, Mar 2026' },
    p_service_leader: {
      buyingRole: 'Economic buyer', reportsTo: 'COO', callMentions: 154,
      caresAbout: ['Cost-to-serve', 'CSAT and NPS', 'Deflection without hurting CX', 'Agent attrition'],
      kpis: ['Average handle time', 'First-contact resolution', 'Deflection rate', 'CSAT'],
      objections: ['\u201COur customers hate bots.\u201D', '\u201COur knowledge base is too messy for AI.\u201D'],
      quote: '\u201CHandle time is up, CSAT is down, and we can\u2019t hire our way out of it.\u201D',
      quoteSource: 'Discovery call \u2014 Grand Hotels & Resorts, Mar 2026' },
    p_cc_ops: {
      buyingRole: 'Technical evaluator', reportsTo: 'VP Support', callMentions: 71,
      caresAbout: ['Queue routing and staffing', 'Knowledge quality', 'QA coverage'],
      kpis: ['Occupancy', 'Schedule adherence', 'Knowledge article usage'],
      objections: ['Integration with telephony and WFM', 'Agent training lift'],
      quote: '\u201COur agents can\u2019t find answers fast enough. Knowledge is scattered everywhere.\u201D',
      quoteSource: 'Inbound email \u2014 Grand Hotels ops, Mar 2026' },
    p_enterprise_architect: {
      buyingRole: 'Technical evaluator', reportsTo: 'CIO', callMentions: 109,
      caresAbout: ['Reuse and composability', 'API governance', 'Avoiding rip-and-replace'],
      kpis: ['API reuse rate', 'Integration delivery time', 'Incidents from brittle integrations'],
      objections: ['\u201CWe can build this with open source.\u201D', 'Platform team capacity'],
      quote: '\u201CWe have 200+ point-to-point integrations. Every change breaks three things.\u201D',
      quoteSource: 'Discovery call \u2014 Pyramid Construction, Mar 2026' },
  };
  D.rows.forEach(r => { if (personas[r.id]) Object.assign(r, personas[r.id]); });

  // ── Ideal Company Profile ──────────────────────────────────────────────
  // Derived from recent closed-won deals per motion.
  function icp(motionId, section, attribute, value, rationale, deals) {
    return { id: motionId + '_' + attribute.toLowerCase().replace(/[^a-z0-9]+/g, '_'), motionId, section, attribute, value, rationale, deals: deals || [] };
  }

  D.icpMeta = {
    data_360_ai_readiness: { deals: 14, medianAcv: '$430K', window: 'Last 4 quarters' },
    sales_cloud_rep_productivity: { deals: 12, medianAcv: '$280K', window: 'Last 4 quarters' },
    agentforce_sales_automation: { deals: 8, medianAcv: '$160K', window: 'Last 3 quarters' },
    service_cloud_contact_center: { deals: 11, medianAcv: '$340K', window: 'Last 4 quarters' },
    mulesoft_integration_modernization: { deals: 9, medianAcv: '$520K', window: 'Last 4 quarters' },
  };

  // ── Additional proof: case studies (sample data modeled on public Salesforce customer stories) ──
  const W = (label, snippet, ref) => ({ type: 'Website', label, snippet, when: 'Mar 12, 2026', ref });
  const newRows = [
    { id: 'cs_f1', category: 'Case Study', proofType: 'Case Study', value: 'Formula 1 \u2014 fan 360',
      description: 'Unified fan data across digital channels and race weekends powers personalized fan engagement at global scale.',
      motionIds: ['data_360_ai_readiness'], products: ['Data 360'], personaSegment: 'CMO \u00b7 CDO \u00b7 Fan engagement leader',
      confidence: 'High', claimType: 'Stated', priority: 'Medium', useCase: 'Customer 360, personalization at scale', safeForOutreach: true,
      sources: [W('F1 customer story', 'Formula 1 unifies fan data to personalize engagement for millions of fans.', 'salesforce.example/customers/formula-1')] },
    { id: 'cs_gucci', category: 'Case Study', proofType: 'Case Study', value: 'Gucci \u2014 AI-assisted client advisors',
      description: 'Client advisors blend service and selling with AI-assisted context, lifting conversion on service interactions.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud', 'Agentforce Service'], personaSegment: 'VP CX \u00b7 Retail service leader',
      confidence: 'High', claimType: 'Stated', priority: 'Medium', useCase: 'AI-assisted service, service-to-sales', safeForOutreach: true,
      sources: [W('Gucci customer story', 'Gucci client advisors use AI-assisted workflows to turn service moments into relationships.', 'salesforce.example/customers/gucci')] },
    { id: 'cs_air_india', category: 'Case Study', proofType: 'Case Study', value: 'Air India \u2014 service modernization',
      description: 'Consolidated service channels and AI-assisted case handling cut resolution times across a fast-growing airline.',
      motionIds: ['service_cloud_contact_center'], products: ['Service Cloud'], personaSegment: 'VP Support \u00b7 Contact center leader',
      confidence: 'Medium', claimType: 'Stated', priority: 'Medium', useCase: 'Channel consolidation, faster resolution', safeForOutreach: true,
      sources: [W('Air India customer story', 'Air India modernized service operations to resolve customer issues faster across channels.', 'salesforce.example/customers/air-india')] },
    { id: 'cs_wiley', category: 'Case Study', proofType: 'Case Study', value: 'Wiley \u2014 Agentforce for support scale',
      description: 'Agentforce resolves routine inquiries during seasonal peaks, raising self-service resolution without added headcount.',
      motionIds: ['agentforce_sales_automation', 'service_cloud_contact_center'], products: ['Agentforce'], personaSegment: 'VP Support \u00b7 AI leader',
      confidence: 'High', claimType: 'Stated', priority: 'High', useCase: 'Agent deflection at seasonal peak', safeForOutreach: true,
      sources: [W('Wiley customer story', 'Wiley uses Agentforce to handle seasonal support surges with higher self-service resolution.', 'salesforce.example/customers/wiley')] },
    { id: 'cs_opentable', category: 'Case Study', proofType: 'Case Study', value: 'OpenTable \u2014 Agentforce concierge',
      description: 'An Agentforce concierge handles diner and restaurant requests end-to-end, freeing teams for complex cases.',
      motionIds: ['agentforce_sales_automation'], products: ['Agentforce'], personaSegment: 'COO \u00b7 Support leader',
      confidence: 'Medium', claimType: 'Stated', priority: 'Medium', useCase: 'End-to-end agent task completion', safeForOutreach: true,
      sources: [W('OpenTable customer story', 'OpenTable\u2019s Agentforce concierge resolves diner requests like reservation changes autonomously within guardrails.', 'salesforce.example/customers/opentable')] },
    { id: 'cs_heathrow', category: 'Case Study', proofType: 'Case Study', value: 'Heathrow \u2014 integration backbone',
      description: 'Reusable APIs connect airport operations systems, speeding delivery of passenger-facing digital services.',
      motionIds: ['mulesoft_integration_modernization'], products: ['MuleSoft'], personaSegment: 'CIO \u00b7 Enterprise architect',
      confidence: 'High', claimType: 'Stated', priority: 'Medium', useCase: 'API reuse, operations integration', safeForOutreach: true,
      sources: [W('Heathrow customer story', 'Heathrow connects operational systems with reusable APIs to ship new passenger services faster.', 'salesforce.example/customers/heathrow')] },

    // ── Additional messaging guardrails ──
    { id: 'guard_no_roi', category: 'Messaging Guardrail', proofType: 'Messaging Guardrail', value: 'No ROI figures without a named customer story',
      description: 'Quantified claims (hours saved, % deflection, revenue lift) may only be used when tied to a published customer story.',
      motionIds: ['sales_cloud_rep_productivity', 'data_360_ai_readiness', 'agentforce_sales_automation'], products: ['All products'], personaSegment: 'All customer-facing messaging',
      confidence: 'High', claimType: 'Stated', priority: 'High', useCase: 'Prevent unsubstantiated ROI claims', safeForOutreach: false,
      sources: [{ type: 'Email', label: 'Legal \u2014 claims review', snippet: '"Any number in outbound must trace to a published, approved story. No exceptions."', when: 'Mar 06, 2026', ref: 'legal review' }] },
    { id: 'guard_no_competitor_names', category: 'Messaging Guardrail', proofType: 'Messaging Guardrail', value: 'Do not name competitors in outbound',
      description: 'Differentiate on capability and trust posture; never name or disparage a competitor in customer-facing messaging.',
      motionIds: ['sales_cloud_rep_productivity', 'service_cloud_contact_center', 'agentforce_sales_automation', 'data_360_ai_readiness', 'mulesoft_integration_modernization'], products: ['All products'], personaSegment: 'All customer-facing messaging',
      confidence: 'High', claimType: 'Stated', priority: 'High', useCase: 'Competitive positioning hygiene', safeForOutreach: false,
      sources: [W('Brand & messaging guidelines', 'Lead with customer outcomes; never reference competitors by name in outbound.', 'salesforce.example/brand/messaging-guidelines')] },
    { id: 'guard_certifications', category: 'Messaging Guardrail', proofType: 'Messaging Guardrail', value: 'Compliance claims must cite official certifications',
      description: 'Security and compliance statements may only reference published certifications and the official trust portal \u2014 never improvised.',
      motionIds: ['data_360_ai_readiness', 'service_cloud_contact_center'], products: ['Data 360', 'Service Cloud'], personaSegment: 'All customer-facing messaging',
      confidence: 'High', claimType: 'Stated', priority: 'High', useCase: 'Security and compliance accuracy', safeForOutreach: false,
      sources: [W('Trust portal', 'Current certifications and compliance documentation are published on the trust portal.', 'salesforce.example/trust/compliance'),
        { type: 'CRM note', label: 'Deal retro \u2014 stalled security review', snippet: 'Rep improvised a compliance answer; deal lost 5 weeks re-validating with security.', when: 'Feb 21, 2026', ref: 'Win/loss notes' }] },
    { id: 'guard_no_timelines', category: 'Messaging Guardrail', proofType: 'Messaging Guardrail', value: 'Do not promise implementation timelines',
      description: 'Timelines depend on customer scope and partners; the agent may share typical ranges only with an explicit "varies by scope" caveat.',
      motionIds: ['mulesoft_integration_modernization', 'sales_cloud_rep_productivity'], products: ['MuleSoft', 'Sales Cloud'], personaSegment: 'All customer-facing messaging',
      confidence: 'Medium', claimType: 'Inferred', priority: 'Medium', useCase: 'Expectation setting', safeForOutreach: false,
      sources: [{ type: 'Call recording', label: 'Deal retro \u2014 Express Logistics', snippet: '"We anchored on 6 weeks in the first call and spent two quarters living it down."', when: 'Feb 14, 2026', ref: 'Gong \u00b7 31 min' }] },
    { id: 'guard_assistive_language', category: 'Messaging Guardrail', proofType: 'Messaging Guardrail', value: 'Describe agents as assistive and permissioned, never autonomous',
      description: 'Approved language: "assists, drafts, recommends, acts within your permissions." Avoid: "autonomous, replaces, decides."',
      motionIds: ['agentforce_sales_automation', 'service_cloud_contact_center'], products: ['Agentforce'], personaSegment: 'All customer-facing messaging',
      confidence: 'High', claimType: 'Stated', priority: 'High', useCase: 'Agent positioning language', safeForOutreach: false,
      sources: [W('Agentforce guidelines', 'Agents operate within customer-defined permissions and human approval workflows.', 'salesforce.example/trust/agentforce-guidelines')] },
    { id: 'guard_regulated', category: 'Messaging Guardrail', proofType: 'Messaging Guardrail', value: 'Regulated-industry workflows require SE review',
      description: 'No claims about HIPAA, FINRA, or other regulated workflows in outbound without solution-engineering review of the account context.',
      motionIds: ['data_360_ai_readiness', 'service_cloud_contact_center'], products: ['Data 360', 'Service Cloud'], personaSegment: 'Healthcare \u00b7 Financial services messaging',
      confidence: 'Medium', claimType: 'Inferred', priority: 'High', useCase: 'Regulated-industry hygiene', safeForOutreach: false,
      sources: [{ type: 'Email', label: 'Legal \u2014 regulated industries', snippet: '"Regulated-workflow claims are SE-reviewed, account-specific, and never templated."', when: 'Mar 03, 2026', ref: 'legal review' }] },
  ];
  newRows.forEach(r => D.rows.push(r));

  D.icp = [
    // ── Data 360 — AI Readiness (14 C/W deals) ──
    icp('data_360_ai_readiness', 'Firmographics', 'Employee count', '2,000 \u2013 50,000',
      'Median closed-won: 8,400 employees. Deals under 1,000 employees closed at a third of the rate.',
      ['Cloud Kicks \u00b7 $480K', 'Pyramid Construction \u00b7 $520K']),
    icp('data_360_ai_readiness', 'Firmographics', 'Annual revenue', '$500M \u2013 $10B',
      'All 14 recent wins fall in this band; below $250M, data team capacity becomes the blocker.',
      ['Northern Trail Outfitters \u00b7 $310K']),
    icp('data_360_ai_readiness', 'Firmographics', 'Industries', 'Retail, Financial services, Healthcare, Manufacturing',
      'Retail and financial services account for 9 of 14 recent wins.',
      ['Cloud Kicks \u00b7 $480K', 'Burlington Textiles \u00b7 $220K']),
    icp('data_360_ai_readiness', 'Firmographics', 'Region', 'North America & EMEA enterprise',
      '12 of 14 wins; APAC deals routed through partner motion.', []),
    icp('data_360_ai_readiness', 'Technographics', 'Data stack', 'Snowflake or Databricks in place',
      'Present in 11 of 14 wins. Zero-copy access was cited as decisive in 6.',
      ['Pyramid Construction \u00b7 $520K', 'United Oil & Gas \u00b7 $740K']),
    icp('data_360_ai_readiness', 'Technographics', 'Salesforce footprint', 'Sales or Service Cloud already deployed',
      '14 of 14 wins \u2014 existing footprint is effectively a prerequisite.', []),
    icp('data_360_ai_readiness', 'Technographics', 'Martech', 'Standalone CDP being consolidated',
      'A CDP replacement or consolidation was in scope in 5 of 14 wins.',
      ['Cloud Kicks \u00b7 $480K']),
    icp('data_360_ai_readiness', 'Buying indicators', 'AI initiative', 'Funded GenAI program in flight',
      '12 of 14 wins had a named, budgeted AI program at time of first call.',
      ['Pyramid Construction \u00b7 $520K', 'Grand Hotels & Resorts \u00b7 $610K']),
    icp('data_360_ai_readiness', 'Buying indicators', 'Buying committee', 'CDO + CIO + security review',
      'Median 6 stakeholders. Security review added 3\u20136 weeks in every deal.', []),
    icp('data_360_ai_readiness', 'Buying indicators', 'Sales cycle', '4 \u2013 7 months',
      'Median 5.2 months from first call to signature.', []),
    icp('data_360_ai_readiness', 'Buying indicators', 'Deal size', '$250K \u2013 $750K ACV',
      'Median $430K. Land typically Data 360 + one activation use case.', []),
    icp('data_360_ai_readiness', 'Poor fit', 'Sub-500-employee single-brand companies', 'Avoid',
      'Zero wins; 7 recent losses in this band cited price.', []),
    icp('data_360_ai_readiness', 'Poor fit', 'No data engineering function', 'Avoid',
      'Implementations stall without a data owner on the customer side.', []),
    icp('data_360_ai_readiness', 'Poor fit', 'Warehouse migration mid-flight', 'Defer',
      'Two stalled deals; revisit once the migration lands.', []),

    // ── Sales Cloud — Rep Productivity (12 C/W deals) ──
    icp('sales_cloud_rep_productivity', 'Firmographics', 'Employee count', '500 \u2013 20,000',
      'Sweet spot is a sales org of 50+ quota-carrying reps; median 140 reps.',
      ['Dickenson plc \u00b7 $390K', 'Express Logistics \u00b7 $270K']),
    icp('sales_cloud_rep_productivity', 'Firmographics', 'Industries', 'Business services, Technology, Logistics, Manufacturing',
      '10 of 12 recent wins; transactional retail underperforms.', []),
    icp('sales_cloud_rep_productivity', 'Firmographics', 'Annual revenue', '$100M \u2013 $5B', 'All 12 wins in band.', []),
    icp('sales_cloud_rep_productivity', 'Technographics', 'CRM posture', 'Salesforce incumbent expanding, or Dynamics displacement',
      '9 of 12 were expansions of an existing org.', ['Dickenson plc \u00b7 $390K']),
    icp('sales_cloud_rep_productivity', 'Technographics', 'Sales stack', 'Engagement-tool sprawl to consolidate',
      'Sprawl (engagement + conversation intelligence + enablement point tools) was the consolidation driver in 7 of 12.', []),
    icp('sales_cloud_rep_productivity', 'Buying indicators', 'Trigger', 'New CRO within first two quarters',
      '7 of 12 wins started within 6 months of a CRO change.',
      ['Express Logistics \u00b7 $270K']),
    icp('sales_cloud_rep_productivity', 'Buying indicators', 'Buying committee', 'CRO + RevOps + IT',
      'Median 4 stakeholders; RevOps is the working champion.', []),
    icp('sales_cloud_rep_productivity', 'Buying indicators', 'Sales cycle', '3 \u2013 5 months', 'Median 3.8 months.', []),
    icp('sales_cloud_rep_productivity', 'Buying indicators', 'Deal size', '$150K \u2013 $450K ACV', 'Median $280K.', []),
    icp('sales_cloud_rep_productivity', 'Poor fit', 'Teams under 25 reps', 'Avoid',
      'ROI math fails below 25 reps; 5 recent losses cite price.', []),

    // ── Agentforce — Sales Agent Automation (8 C/W deals) ──
    icp('agentforce_sales_automation', 'Firmographics', 'Employee count', '1,000 \u2013 30,000',
      'All 8 wins; smaller orgs lack the data foundation.', ['Grand Hotels & Resorts \u00b7 $610K']),
    icp('agentforce_sales_automation', 'Firmographics', 'Industries', 'Technology, Hospitality, Financial services',
      '7 of 8 recent wins.', []),
    icp('agentforce_sales_automation', 'Technographics', 'CRM maturity', 'Mature Sales Cloud org with clean data',
      'Clean CRM data was a stated prerequisite in 8 of 8; two failed pilots elsewhere traced to messy data.', []),
    icp('agentforce_sales_automation', 'Technographics', 'Data foundation', 'Data 360 or equivalent unified profile',
      'Present in 6 of 8 wins; strongest attach motion.', ['Cloud Kicks \u00b7 $480K']),
    icp('agentforce_sales_automation', 'Buying indicators', 'Budget', 'Funded AI budget line',
      '8 of 8 had explicit AI budget; none were displacement of headcount budget.', []),
    icp('agentforce_sales_automation', 'Buying indicators', 'Sponsor', 'C-level exec sponsor',
      'Every win had CRO or CEO sponsorship; director-led evaluations stalled.', []),
    icp('agentforce_sales_automation', 'Buying indicators', 'Sales cycle', '2 \u2013 4 months',
      'Land small (single use case), expand after first measurable win.', []),
    icp('agentforce_sales_automation', 'Buying indicators', 'Deal size', '$80K \u2013 $300K initial ACV', 'Median $160K initial.', []),
    icp('agentforce_sales_automation', 'Poor fit', 'Messy CRM data', 'Defer',
      'Route to Sales Cloud hygiene motion first.', []),
    icp('agentforce_sales_automation', 'Poor fit', 'No legal framework for AI outreach', 'Defer',
      'Two deals stalled in legal for 90+ days.', []),

    // ── Service Cloud — Contact Center Modernization (11 C/W deals) ──
    icp('service_cloud_contact_center', 'Firmographics', 'Contact center size', '100+ seats (median 320)',
      'All 11 wins; below 100 seats the deflection ROI shrinks.', ['Grand Hotels & Resorts \u00b7 $610K']),
    icp('service_cloud_contact_center', 'Firmographics', 'Industries', 'Hospitality, Retail, Telecom, Utilities',
      '9 of 11 recent wins are high-volume B2C.', []),
    icp('service_cloud_contact_center', 'Firmographics', 'Employee count', '1,000+', 'All 11 wins.', []),
    icp('service_cloud_contact_center', 'Technographics', 'Current stack', 'Legacy on-prem telephony or aging helpdesk',
      '8 of 11 were displacements of on-prem or end-of-life systems.', []),
    icp('service_cloud_contact_center', 'Technographics', 'Knowledge base', 'Exists but fragmented',
      'A messy-but-present KB is the ideal entry condition for AI-assisted service.', []),
    icp('service_cloud_contact_center', 'Buying indicators', 'Mandate', 'Cost-reduction or efficiency program',
      '9 of 11 wins had a stated cost-to-serve mandate.', ['Grand Hotels & Resorts \u00b7 $610K']),
    icp('service_cloud_contact_center', 'Buying indicators', 'Buying committee', 'VP Support + IT + Procurement',
      'Procurement involvement from week one in 10 of 11.', []),
    icp('service_cloud_contact_center', 'Buying indicators', 'Sales cycle', '4 \u2013 6 months', 'Median 4.9 months.', []),
    icp('service_cloud_contact_center', 'Buying indicators', 'Deal size', '$200K \u2013 $600K ACV', 'Median $340K.', []),
    icp('service_cloud_contact_center', 'Poor fit', 'Under 25 support seats', 'Avoid', 'No recent wins below 25 seats.', []),

    // ── MuleSoft — Integration Modernization (9 C/W deals) ──
    icp('mulesoft_integration_modernization', 'Firmographics', 'Employee count', '2,000+',
      'All 9 wins; integration complexity scales with org size.', ['United Oil & Gas \u00b7 $740K']),
    icp('mulesoft_integration_modernization', 'Firmographics', 'Industries', 'Financial services, Energy, Manufacturing, Healthcare',
      '8 of 9 recent wins.', []),
    icp('mulesoft_integration_modernization', 'Firmographics', 'M&A activity', 'Acquisition in past 24 months',
      'Present in 6 of 9 wins \u2014 the strongest single predictor.',
      ['Pyramid Construction \u00b7 $520K']),
    icp('mulesoft_integration_modernization', 'Technographics', 'App portfolio', '100+ applications',
      'Median 240 apps across recent wins.', []),
    icp('mulesoft_integration_modernization', 'Technographics', 'Middleware', 'Legacy ESB or middleware to retire',
      '7 of 9 wins displaced an aging ESB.', []),
    icp('mulesoft_integration_modernization', 'Buying indicators', 'Trigger', 'M&A integration or ERP migration',
      'One of the two present in every recent win.', ['United Oil & Gas \u00b7 $740K']),
    icp('mulesoft_integration_modernization', 'Buying indicators', 'Buying committee', 'Enterprise architect + CIO + platform team',
      'Architect-led evaluations; CIO signs.', []),
    icp('mulesoft_integration_modernization', 'Buying indicators', 'Sales cycle', '5 \u2013 8 months', 'Median 6.1 months.', []),
    icp('mulesoft_integration_modernization', 'Buying indicators', 'Deal size', '$300K \u2013 $900K ACV', 'Median $520K.', []),
    icp('mulesoft_integration_modernization', 'Poor fit', 'Greenfield or single-vendor stacks', 'Avoid',
      'No integration debt, no urgency.', []),
  ];

  // ── GTM motions (sales plays — may cut across products; optional layer) ──
  D.plays = [
    { id: 'play_ai_transformation', name: 'AI Transformation', products: ['Data 360', 'Agentforce'],
      motionIds: ['data_360_ai_readiness', 'agentforce_sales_automation'], icpMotionId: 'data_360_ai_readiness' },
    { id: 'play_seller_productivity', name: 'Seller Productivity', products: ['Sales Cloud', 'Agentforce Sales'],
      motionIds: ['sales_cloud_rep_productivity', 'agentforce_sales_automation'], icpMotionId: 'sales_cloud_rep_productivity' },
    { id: 'play_post_ma', name: 'Post-M&A Integration', products: ['MuleSoft', 'Data 360'],
      motionIds: ['mulesoft_integration_modernization', 'data_360_ai_readiness'], icpMotionId: 'mulesoft_integration_modernization' },
  ];
})();
